feat : geojson api 설계 (해결 중) -1
Hipspot/hipspot-backend pull request #4
Opened 2023-01-29 04:26 UTC by rivkode

```
//카페 1개에 대한 geojson 데이터
[{
  "properties": {
    "instaId": String,
    "id": Number,
    "placeName": String,
		"filterId":Number,
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      127.051352,
      37.5446694
    ]
  },
  "type": "Feature"
}]
```

의 요구사항대로 api 설계 중 dto 타입 설정 에러

2023-01-29 04:41 UTC, InHyeok-J commented
커밋 변화가 뭐 거의 없어서 리뷰를 볼수가 없네요 ㅎ;

controller에서 GeojsonResponseDto 를 리턴하려면 어떻게 해야 할까요 ? 저 형식대로 처리하려면..
GeojsonResponseDto 의 배열 형태로 리턴이 되어야 하니 controller의 반환 타입은 List< GeojsonResponseDto> 여야겠죠?

GeojsonResponseDto의 가장 큰 내용은 뭘까요 ? properties, geometry, type 이네요
그럼 각각의 속성의 타입은 어떻게 될까요 ? 
properties -> 현재 있는 Properties 타입을 쓰면 될거같고
geomety는 Geomety 타입을 하나 만들어야 겠네요 
type -> String or enum

그리고 geomety는  type 이랑 coordinates 속성이 있네요 이젠 아실거라고 생각합니다 
@rivkode

2023-01-29 14:33 UTC, rivkode commented
@Sangjun-man @InHyeok-J @jiwonidooly
아래와 같이 dto를 활용해서 api 설계 완료하였습니다

![image](https://user-images.githubusercontent.com/109144975/215333459-e88bd515-7ff0-4f0c-a560-a81280285ead.png)

merge 해도 되는지 확인 부탁드립니다

2023-01-30 00:15 UTC, InHyeok-J requested changes
수정해서 올려주세요.

2023-01-30 00:15 UTC, InHyeok-J commented on src/main/java/com/hipspot/web/dto/Type.java
> +}
Type이라는 클래스를 따로 만든 이유가 뭘까요 ? 
API 형식과 다른 형태인거같은데

2023-01-30 00:15 UTC, InHyeok-J commented on src/main/java/com/hipspot/domain/cafes/Geojsons.java
>       */
안쓰는 주석은 삭제하는게 좋아보이네요 밑에도 동일합니다

2023-01-30 00:15 UTC, InHyeok-J commented on src/main/java/com/hipspot/web/dto/Geometry.java
> +    }
Gemetry는 Dto Type이면 기존 DTO 클래스의 컨벤션과 같이 통일시키는게 좋아보입니다, properties도 마찬가지고요

2023-01-30 00:15 UTC, InHyeok-J commented on src/main/java/com/hipspot/service/cafes/GeojsonsService.java
>      }
해당 부분에 몇 가지 의문점이 있습니다.
1. 현재 단건 조회(findById)인데 왜 List형식인지? , 만약 공통된 응답 포맷이 List면 중복 제거 후 공통 처리를 하는게 좋아보여요, service코드에서 중요하지 않는, 응답 형태 포맷이  대부분의 코드를 차지하네요.

2.  
```
 List<Long> coordinates = new ArrayList<>();
coordinates.add(entity.getLatitude());
coordinates.add(entity.getLongitude());

Properties properties = new Properties(entity);
Geometry geometry = new Geometry("Point", coordinates);
Type type = new Type("Feature");
```
여기 있는 모든 로직 다 1번에 해당하는 비지니스 로직 외 불필요한 코드들입니다.

GeojsonResponseDto의 생성자 안에서 처리하는건 어떨까요 ?

3. Type이 feature라고 적었는데 Feature는 어떤 의미로 사용한걸까요 ? 그 외에 다른 부분은 뭐가 있나요?
만약 클라이언트와 논의한 내용이면 enum 값으로 상수를 처리하는게 어떨까요? 이건 Gemetry의 "Point" 도 해당하는 부분입니다.

전체적으로 Service 코드에 불필요한게 너무 많아 보이네요.

2023-02-05 08:30 UTC, rivkode reviewed
1. 서비스 코드에서 불필요한 코드를 줄이고 데이터 처리를 dto 생성자 내에서 해결하였습니다.
2. enum을 사용하여 type 속성을 입력하였습니다.
3. 요구사항이 지정한 geojsonresponseDto 형식인 data 전체 가져오는 것입니다. 여기서 repository 에 있는 모든 데이터를 가져올때 실패하였습니다. repository 사용법을 더 찾아보겠습니다.

2023-02-06 03:30 UTC, InHyeok-J approved these changes
도메인에 대해 논의 후에 DTO랑 이런거 다시 상의하시고 이슈 파서 리팩토링 하는게 좋아보이네요 수고하셨습니다

2023-02-06 03:30 UTC, InHyeok-J commented on src/main/java/com/hipspot/web/dto/Type.java
> +}
이 Type이라는 친구가 무슨 의미인지 잘 모르겠네요.. 보니깐 기획 관련된거 프론트랑상의가 필요한거 같은데... dto가 클라가 막 요구한다고 아무런 이해 없이 짜면 안될거같아요 . 다음에는 회의를 통해 왜 값이 필요하고 불필요한지를 정하면 좋을 거 같네요...

2023-02-06 03:33 UTC, InHyeok-J commented
@rivkode 
>  enum .. 찾아보고 상수로 처리하겠습니다. Type Feature 로 처리한건 물어보니 geojson 데이터가 저 타입을 필요로 해서 라고 알고 있는데 혹시 답변 가능한가요 ? (상준)


이러면 안됩니다. 제가 알기로 dto 회의를 한걸로 알고 있는데 왜 클라이언트를 언급을 하나요? 백엔드 개발자라면 도메인에 대한 이해와 더불어 dto 상의를 했으면 왜 값이 필요한지 알고 개발을 시작해야죠..

2023-02-06 03:49 UTC, rivkode commented on src/main/java/com/hipspot/web/dto/Type.java
> +}
넵 프론트와 dto에 대해 다시 상의를 하여서 이해 후 작성해보겠습니다

2023-02-11 18:48 UTC, rivkode commented
> @rivkode
> 
> > enum .. 찾아보고 상수로 처리하겠습니다. Type Feature 로 처리한건 물어보니 geojson 데이터가 저 타입을 필요로 해서 라고 알고 있는데 혹시 답변 가능한가요 ? (상준)
> 
> 이러면 안됩니다. 제가 알기로 dto 회의를 한걸로 알고 있는데 왜 클라이언트를 언급을 하나요? 백엔드 개발자라면 도메인에 대한 이해와 더불어 dto 상의를 했으면 왜 값이 필요한지 알고 개발을 시작해야죠..

@InHyeok-J 넵 Dto 관련해서는 회의 후 리팩토링을 해나가겠습니다.
info, geojson API 구현 완료하였습니다
데이터 가공하는데 시간이 조금 걸리고 dto에 수정사항이 있었어서 수정 완료하였습니다.
확인해주시면 merge 하겠습니다.

2023-02-12 12:27 UTC, InHyeok-J commented
네 머지하셔도 돼요

2023-02-12 13:02 UTC, merged